spring:
  redis:
    host: 172.20.24.130
    port: 6379
    password: 651tkoOuMeQzxLZfFUAv
  datasource:
    url: jdbc:mysql://172.20.2.123:3306/driving_report?serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: arcfox
    password: TIMA_arcfox_2019
  jpa:
    properties:
      #数据库方言
      hibernate.dialect: org.hibernate.dialect.MySQL55Dialect
      #是否打印sql
      hibernate.show_sql: false
      #是否格式化sql
      hibernate.format_sql: true
      #指出什么操作产生的 SQL
      hibernate.use_sql_comments: true
      #数据库更新方式
      hibernate.hbm2ddl.auto: update
      hibernate:
        naming:
          # 该属性定义映射domain到表时使用的名称转换规则，如果不使用如下配置，spring boot会采用默认配置，会将表名，字段名按照spring的风格来定义。
          # 以至于它会忽略@Table，@Column中定义的名字的大小写。当然，可以采用spring推荐的命名法，详见77.6节
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl