spring:
  datasource:
    druid:
      url: jdbc:mysql://172.20.24.130:3306/RUGE?useUnicode=true&characterEncoding=utf-8
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: fawblocseaoutdev
      password: q6mc7eP9LSMuRXoo4vC4
      min-idle: 2
      max-active: 10
      initial-size: 2
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true

