spring:
  kafka:
    bootstrap-servers: 172.20.24.129:9092
    consumer:
      group-id: 0
      enable-auto-commit: true
      auto-offset-reset: earliest
    producer:
      batch-size: 16384
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 10
