spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      max-poll-records: 200
      heartbeat-interval: 9000
      group-id: jpush
      enable-auto-commit: true
      auto-offset-reset: earliest
    producer:
      batch-size: 16384
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      retries: 10

server:
  port: 8081
